sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4.2
branches:
  only:
    - master
before_install:
  - npm i -g npm@^3.0.0
  - npm i -g nyc@^7.0.0
  - npm i -g codecov@^1.0.0
  - npm i -g semantic-release@^4.3.5
before_script:
  - npm prune
script:
  - npm run check
after_success:
  - nyc report --report-dir=./coverage --reporter=text-lcov > ./coverage/coverage.lcov
  - codecov
  - semantic-release pre
  - npm publish
  - semantic-release post
