sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4.2
before_install:
  - npm i -g npm@^3.0.0
  - npm i -g nyc@^7.0.0
  - npm i -g codecov@^1.0.0
  - npm i -g semantic-release@^4.3.5
install:
  - npm i
before_script:
  - npm prune
script:
  - npm run check
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      npm run build;
      nyc report --report-dir=./coverage --reporter=text-lcov > ./coverage/coverage.lcov;
      codecov;
      semantic-release pre;
      npm publish;
      semantic-release post;
    fi
