
/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    Account Events

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */


/**
 *  Account Events
 */
const AccountEvents = {
    ACCOUNT_CREATION_STARTED: 'ACCOUNT_CREATION_STARTED',
    ACCOUNT_CREATION_FAILED: 'ACCOUNT_CREATION_FAILED',
    ACCOUNT_CREATED: 'ACCOUNT_CREATED',

    ACCOUNT_EMAIL_CHANGE_STARTED: 'ACCOUNT_EMAIL_CHANGE_STARTED',
    ACCOUNT_EMAIL_CHANGE_FAILED: 'ACCOUNT_EMAIL_CHANGE_FAILED',
    ACCOUNT_EMAIL_CHANGED: 'ACCOUNT_EMAIL_CHANGED',

    ACCOUNT_PASSWORD_CHANGE_STARTED: 'ACCOUNT_PASSWORD_CHANGE_STARTED',
    ACCOUNT_PASSWORD_CHANGE_FAILED: 'ACCOUNT_PASSWORD_CHANGE_FAILED',
    ACCOUNT_PASSWORD_CHANGED: 'ACCOUNT_PASSWORD_CHANGED',

    ACCOUNT_PASSWORD_RESET_STARTED: 'ACCOUNT_PASSWORD_RESET_STARTED',
    ACCOUNT_PASSWORD_RESET_FAILED: 'ACCOUNT_PASSWORD_RESET_FAILED',
    ACCOUNT_PASSWORD_RESET: 'ACCOUNT_PASSWORD_RESET',

    ACCOUNT_DELETION_STARTED: 'ACCOUNT_DELETION_STARTED',
    ACCOUNT_DELETION_FAILED: 'ACCOUNT_DELETION_FAILED',
    ACCOUNT_DELETED: 'ACCOUNT_DELETED'
};

// Export Account Events
export default AccountEvents;
